spring.application.name=perecederos-demo

spring.datasource.url=jdbc:postgresql://db:5432/caducidadesdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Cambia 'none' a 'update' para que Hibernate cree las tablas nuevas (como los detalles de los CEDIS)
spring.jpa.hibernate.ddl-auto=update

# Propiedades de paciencia para Docker (Evita el "Connection Closed")
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never